layout: sidebar
style: dark
url: "https://noa.dev"
plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

repositories: 
  - MineReset
  - SimpleWarp
  - mcpeme
  - lecture-buddy
  - vanfringe-browser
  - pairr
  - nofear
  - cw
  - more-options

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
